### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by aligulzar729** [shuvroroy/filament-spatie-laravel-backup#14]
Hey,
I'm using your plugin for backup and using PostgresSQL with Laragon on Windows and latest filament I get error of "could not find driver" when I open Backups page.

**Comment by bernhardh** [comment]
Same here just on ubuntu, php8 and mysql.

**Comment by bernhardh** [comment]
Ok, found and solved it. This package uses the https://github.com/calebporzio/sushi packages under the hood, which itself requires sqllite. The error message is not really helpfull, but it dies because of the missing sqllite driver. So just install it on your maschine/server:

```
sudo apt install php8.0-sqlite
```

And afterwards restart your http server (apache2/nginx)..

**Comment by aligulzar729** [comment]
@bernhardh Thanks its fixed after enabling pdo_sqlite and sqlite3 extensions from laragon.

**Comment by mokhosh** [comment]
Just for other people who might end up here, in case `sudo apt install php8.3-sqlite` didn't work for you, try this:
```bash
sudo apt install php8.3-sqlite3
```
